apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-auth
  namespace: jupyter
type: Opaque
stringData:
  users.json: |
    {
      "admin": "Admin@123456",
      "user1": "User1@123456",
      "user2": "User2@123456"
    }
