apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-shared-cluster.fullname" . }}-conf
  namespace: {{ .Release.Namespace }}
data:
  fairscheduler.xml: |
{{ .Values.fairSchedulerXml | indent 4 }}
